#!/bin/bash

echo "Testing echo success"
curl -s -F 'file=@matrix.csv' "localhost:8080/echo"
echo ""
echo "Testing echo failure"
curl -s -F 'file=@matrix_not_squared.csv' "localhost:8080/echo"
echo ""
echo "Testing echo failure"
curl -s -F 'file=@matrix_parse_error.csv' "localhost:8080/echo"
echo ""
echo "Testing echo failure"
curl -s -F 'file=@matrix_not_integer.csv' "localhost:8080/echo"
echo ""
echo ""

echo "Testing invert success"
curl -s -F 'file=@matrix.csv' "localhost:8080/invert"
echo "Testing invert failure"
curl -s -F 'file=@matrix_not_squared.csv' "localhost:8080/invert"
echo ""
echo "Testing invert failure"
curl -s -F 'file=@matrix_parse_error.csv' "localhost:8080/invert"
echo ""
echo "Testing invert failure"
curl -s -F 'file=@matrix_not_integer.csv' "localhost:8080/invert"
echo ""
echo ""

echo "Testing flatten success"
curl -s -F 'file=@matrix.csv' "localhost:8080/flatten"
echo ""
echo "Testing flatten failure"
curl -s -F 'file=@matrix_not_squared.csv' "localhost:8080/flatten"
echo ""
echo "Testing flatten failure"
curl -s -F 'file=@matrix_parse_error.csv' "localhost:8080/flatten"
echo ""
echo "Testing flatten failure"
curl -s -F 'file=@matrix_not_integer.csv' "localhost:8080/flatten"
echo ""
echo ""

echo "Testing sum success"
curl -s -F 'file=@matrix.csv' "localhost:8080/sum"
echo ""
echo "Testing sum failure"
curl -s -F 'file=@matrix_not_squared.csv' "localhost:8080/sum"
echo ""
echo "Testing sum failure"
curl -s -F 'file=@matrix_parse_error.csv' "localhost:8080/sum"
echo ""
echo "Testing sum failure"
curl -s -F 'file=@matrix_not_integer.csv' "localhost:8080/sum"

echo ""
echo ""
echo "Testing multiply success"
curl -s -F 'file=@matrix.csv' "localhost:8080/multiply"
echo ""
echo "Testing multiply failure"
curl -s -F 'file=@matrix_not_squared.csv' "localhost:8080/multiply"
echo ""
echo "Testing multiply failure"
curl -s -F 'file=@matrix_parse_error.csv' "localhost:8080/multiply"
echo ""
echo "Testing multiply failure"
curl -s -F 'file=@matrix_not_integer.csv' "localhost:8080/multiply"